# Generated by Django 3.2.9 on 2021-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='昵称', max_length=64, unique=True, verbose_name='昵称')),
                ('avatar', models.ImageField(help_text='头像', upload_to='avatar', verbose_name='头像')),
                ('password_md5', models.CharField(help_text='md5后密码', max_length=32, verbose_name='md5后密码')),
                ('description', models.TextField(default='', help_text='介绍', verbose_name='介绍')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
